# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T10:27:04+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity
from fastapi import Header, Path, Query
from pydantic import conint, constr

from models import (
    AccessDeniedException,
    AddProfileKeyResponse,
    BadRequestException,
    CreateDomainResponse,
    CreateIntegrationWorkflowResponse,
    CreateProfileResponse,
    DeleteDomainResponse,
    DeleteIntegrationResponse,
    DeleteProfileKeyResponse,
    DeleteProfileObjectResponse,
    DeleteProfileObjectTypeResponse,
    DeleteProfileResponse,
    DeleteWorkflowResponse,
    DomainsDomainNameIdentityResolutionJobsAutoMergingPreviewPostRequest,
    DomainsDomainNameIntegrationsDeletePostRequest,
    DomainsDomainNameIntegrationsPostRequest,
    DomainsDomainNameIntegrationsPutRequest,
    DomainsDomainNameObjectTypesObjectTypeNamePutRequest,
    DomainsDomainNamePostRequest,
    DomainsDomainNameProfilesDeletePostRequest,
    DomainsDomainNameProfilesKeysDeletePostRequest,
    DomainsDomainNameProfilesKeysPostRequest,
    DomainsDomainNameProfilesObjectsDeletePostRequest,
    DomainsDomainNameProfilesObjectsMergePostRequest,
    DomainsDomainNameProfilesObjectsPostRequest,
    DomainsDomainNameProfilesObjectsPutRequest,
    DomainsDomainNameProfilesPostRequest,
    DomainsDomainNameProfilesPutRequest,
    DomainsDomainNameProfilesSearchPostRequest,
    DomainsDomainNamePutRequest,
    DomainsDomainNameWorkflowsIntegrationsPostRequest,
    DomainsDomainNameWorkflowsPostRequest,
    GetAutoMergingPreviewResponse,
    GetDomainResponse,
    GetIdentityResolutionJobResponse,
    GetIntegrationResponse,
    GetMatchesResponse,
    GetProfileObjectTypeResponse,
    GetProfileObjectTypeTemplateResponse,
    GetWorkflowResponse,
    GetWorkflowStepsResponse,
    IntegrationsPostRequest,
    InternalServerException,
    ListAccountIntegrationsResponse,
    ListDomainsResponse,
    ListIdentityResolutionJobsResponse,
    ListIntegrationsResponse,
    ListProfileObjectsResponse,
    ListProfileObjectTypesResponse,
    ListProfileObjectTypeTemplatesResponse,
    ListTagsForResourceResponse,
    ListWorkflowsResponse,
    MergeProfilesResponse,
    PutIntegrationResponse,
    PutProfileObjectResponse,
    PutProfileObjectTypeResponse,
    ResourceNotFoundException,
    SearchProfilesResponse,
    TagKeys,
    TagResourceResponse,
    TagsResourceArnPostRequest,
    ThrottlingException,
    UntagResourceResponse,
    UpdateDomainResponse,
    UpdateProfileResponse,
)

app = MCPProxy(
    contact={
        'email': 'mike.ralphson@gmail.com',
        'name': 'Mike Ralphson',
        'url': 'https://github.com/mermade/aws2openapi',
        'x-twitter': 'PermittedSoc',
    },
    description='<fullname>Amazon Connect Customer Profiles</fullname> <p>Amazon Connect Customer Profiles is a unified customer profile for your contact center that has pre-built connectors powered by AppFlow that make it easy to combine customer information from third party applications, such as Salesforce (CRM), ServiceNow (ITSM), and your enterprise resource planning (ERP), with contact history from your Amazon Connect contact center. If you\'re new to Amazon Connect, you might find it helpful to review the <a href="https://docs.aws.amazon.com/connect/latest/adminguide/">Amazon Connect Administrator Guide</a>.</p>',
    license={'name': 'Apache 2.0 License', 'url': 'http://www.apache.org/licenses/'},
    termsOfService='https://aws.amazon.com/service-terms/',
    title='Amazon Connect Customer Profiles',
    version='2020-08-15',
    servers=[
        {
            'description': 'The Customer Profiles multi-region endpoint',
            'url': 'http://profile.{region}.amazonaws.com',
            'variables': {
                'region': {
                    'default': 'us-east-1',
                    'description': 'The AWS region',
                    'enum': [
                        'us-east-1',
                        'us-east-2',
                        'us-west-1',
                        'us-west-2',
                        'us-gov-west-1',
                        'us-gov-east-1',
                        'ca-central-1',
                        'eu-north-1',
                        'eu-west-1',
                        'eu-west-2',
                        'eu-west-3',
                        'eu-central-1',
                        'eu-south-1',
                        'af-south-1',
                        'ap-northeast-1',
                        'ap-northeast-2',
                        'ap-northeast-3',
                        'ap-southeast-1',
                        'ap-southeast-2',
                        'ap-east-1',
                        'ap-south-1',
                        'sa-east-1',
                        'me-south-1',
                    ],
                }
            },
        },
        {
            'description': 'The Customer Profiles multi-region endpoint',
            'url': 'https://profile.{region}.amazonaws.com',
            'variables': {
                'region': {
                    'default': 'us-east-1',
                    'description': 'The AWS region',
                    'enum': [
                        'us-east-1',
                        'us-east-2',
                        'us-west-1',
                        'us-west-2',
                        'us-gov-west-1',
                        'us-gov-east-1',
                        'ca-central-1',
                        'eu-north-1',
                        'eu-west-1',
                        'eu-west-2',
                        'eu-west-3',
                        'eu-central-1',
                        'eu-south-1',
                        'af-south-1',
                        'ap-northeast-1',
                        'ap-northeast-2',
                        'ap-northeast-3',
                        'ap-southeast-1',
                        'ap-southeast-2',
                        'ap-east-1',
                        'ap-south-1',
                        'sa-east-1',
                        'me-south-1',
                    ],
                }
            },
        },
        {
            'description': 'The Customer Profiles endpoint for China (Beijing) and China (Ningxia)',
            'url': 'http://profile.{region}.amazonaws.com.cn',
            'variables': {
                'region': {
                    'default': 'cn-north-1',
                    'description': 'The AWS region',
                    'enum': ['cn-north-1', 'cn-northwest-1'],
                }
            },
        },
        {
            'description': 'The Customer Profiles endpoint for China (Beijing) and China (Ningxia)',
            'url': 'https://profile.{region}.amazonaws.com.cn',
            'variables': {
                'region': {
                    'default': 'cn-north-1',
                    'description': 'The AWS region',
                    'enum': ['cn-north-1', 'cn-northwest-1'],
                }
            },
        },
    ],
)


@app.get(
    '/domains',
    description=""" Returns a list of all the domains for an AWS account that have been created. """,
    tags=['identity_resolution_jobs'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def list_domains(
    next_token: Optional[constr(min_length=1, max_length=1024)] = Query(
        None, alias='next-token'
    ),
    max_results: Optional[conint(ge=1, le=100)] = Query(None, alias='max-results'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/domains/{DomainName}',
    description=""" Deletes a specific domain and all of its customer data, such as customer profile attributes and their related objects. """,
    tags=['domain_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def delete_domain(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/domains/{DomainName}',
    description=""" Returns information about a specific domain. """,
    tags=['domain_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def get_domain(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/domains/{DomainName}',
    description=""" <p>Creates a domain, which is a container for all customer data, such as customer profile attributes, object types, profile keys, and encryption keys. You can create multiple domains, and each domain can have multiple third-party integrations.</p> <p>Each Amazon Connect instance can be associated with only one domain. Multiple Amazon Connect instances can be associated with one domain.</p> <p>Use this API or <a href="https://docs.aws.amazon.com/customerprofiles/latest/APIReference/API_UpdateDomain.html">UpdateDomain</a> to enable <a href="https://docs.aws.amazon.com/customerprofiles/latest/APIReference/API_GetMatches.html">identity resolution</a>: set <code>Matching</code> to true. </p> <p>To prevent cross-service impersonation when you call this API, see <a href="https://docs.aws.amazon.com/connect/latest/adminguide/cross-service-confused-deputy-prevention.html">Cross-service confused deputy prevention</a> for sample policies that you should apply. </p> """,
    tags=['domain_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def create_domain(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: DomainsDomainNamePostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/domains/{DomainName}',
    description=""" <p>Updates the properties of a domain, including creating or selecting a dead letter queue or an encryption key.</p> <p>After a domain is created, the name can’t be changed.</p> <p>Use this API or <a href="https://docs.aws.amazon.com/customerprofiles/latest/APIReference/API_CreateDomain.html">CreateDomain</a> to enable <a href="https://docs.aws.amazon.com/customerprofiles/latest/APIReference/API_GetMatches.html">identity resolution</a>: set <code>Matching</code> to true. </p> <p>To prevent cross-service impersonation when you call this API, see <a href="https://docs.aws.amazon.com/connect/latest/adminguide/cross-service-confused-deputy-prevention.html">Cross-service confused deputy prevention</a> for sample policies that you should apply. </p> <p>To add or remove tags on an existing Domain, see <a href="https://docs.aws.amazon.com/customerprofiles/latest/APIReference/API_TagResource.html">TagResource</a>/<a href="https://docs.aws.amazon.com/customerprofiles/latest/APIReference/API_UntagResource.html">UntagResource</a>.</p> """,
    tags=['domain_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def update_domain(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: DomainsDomainNamePutRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/domains/{DomainName}/identity-resolution-jobs',
    description=""" Lists all of the Identity Resolution Jobs in your domain. The response sorts the list by <code>JobStartTime</code>. """,
    tags=['domain_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def list_identity_resolution_jobs(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    next_token: Optional[constr(min_length=1, max_length=1024)] = Query(
        None, alias='next-token'
    ),
    max_results: Optional[conint(ge=1, le=100)] = Query(None, alias='max-results'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/domains/{DomainName}/identity-resolution-jobs/auto-merging-preview',
    description=""" <p>Tests the auto-merging settings of your Identity Resolution Job without merging your data. It randomly selects a sample of matching groups from the existing matching results, and applies the automerging settings that you provided. You can then view the number of profiles in the sample, the number of matches, and the number of profiles identified to be merged. This enables you to evaluate the accuracy of the attributes in your matching list. </p> <p>You can't view which profiles are matched and would be merged.</p> <important> <p>We strongly recommend you use this API to do a dry run of the automerging process before running the Identity Resolution Job. Include <b>at least</b> two matching attributes. If your matching list includes too few attributes (such as only <code>FirstName</code> or only <code>LastName</code>), there may be a large number of matches. This increases the chances of erroneous merges.</p> </important> """,
    tags=['domain_management', 'identity_resolution_jobs'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def get_auto_merging_preview(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: DomainsDomainNameIdentityResolutionJobsAutoMergingPreviewPostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/domains/{DomainName}/identity-resolution-jobs/{JobId}',
    description=""" <p>Returns information about an Identity Resolution Job in a specific domain. </p> <p>Identity Resolution Jobs are set up using the Amazon Connect admin console. For more information, see <a href="https://docs.aws.amazon.com/connect/latest/adminguide/use-identity-resolution.html">Use Identity Resolution to consolidate similar profiles</a>.</p> """,
    tags=['identity_resolution_jobs'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def get_identity_resolution_job(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    job_id: constr(pattern=r'[a-f0-9]{32}') = Path(..., alias='JobId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/domains/{DomainName}/integrations',
    description=""" Lists all of the integrations in your domain. """,
    tags=['domain_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def list_integrations(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    next_token: Optional[constr(min_length=1, max_length=1024)] = Query(
        None, alias='next-token'
    ),
    max_results: Optional[conint(ge=1, le=100)] = Query(None, alias='max-results'),
    include_hidden: Optional[bool] = Query(None, alias='include-hidden'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/domains/{DomainName}/integrations',
    description=""" Returns an integration for a domain. """,
    tags=['domain_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def get_integration(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: DomainsDomainNameIntegrationsPostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/domains/{DomainName}/integrations',
    description=""" <p>Adds an integration between the service and a third-party service, which includes Amazon AppFlow and Amazon Connect.</p> <p>An integration can belong to only one domain.</p> <p>To add or remove tags on an existing Integration, see <a href="https://docs.aws.amazon.com/customerprofiles/latest/APIReference/API_TagResource.html"> TagResource </a>/<a href="https://docs.aws.amazon.com/customerprofiles/latest/APIReference/API_UntagResource.html"> UntagResource</a>.</p> """,
    tags=['domain_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def put_integration(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: DomainsDomainNameIntegrationsPutRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/domains/{DomainName}/integrations/delete',
    description=""" Removes an integration from a specific domain. """,
    tags=['domain_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def delete_integration(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: DomainsDomainNameIntegrationsDeletePostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/domains/{DomainName}/matches',
    description=""" <p>Before calling this API, use <a href="https://docs.aws.amazon.com/customerprofiles/latest/APIReference/API_CreateDomain.html">CreateDomain</a> or <a href="https://docs.aws.amazon.com/customerprofiles/latest/APIReference/API_UpdateDomain.html">UpdateDomain</a> to enable identity resolution: set <code>Matching</code> to true.</p> <p>GetMatches returns potentially matching profiles, based on the results of the latest run of a machine learning process. </p> <important> <p>The process of matching duplicate profiles. If <code>Matching</code> = <code>true</code>, Amazon Connect Customer Profiles starts a weekly batch process called Identity Resolution Job. If you do not specify a date and time for Identity Resolution Job to run, by default it runs every Saturday at 12AM UTC to detect duplicate profiles in your domains. </p> <p>After the Identity Resolution Job completes, use the <a href="https://docs.aws.amazon.com/customerprofiles/latest/APIReference/API_GetMatches.html">GetMatches</a> API to return and review the results. Or, if you have configured <code>ExportingConfig</code> in the <code>MatchingRequest</code>, you can download the results from S3.</p> </important> <p>Amazon Connect uses the following profile attributes to identify matches:</p> <ul> <li> <p>PhoneNumber</p> </li> <li> <p>HomePhoneNumber</p> </li> <li> <p>BusinessPhoneNumber</p> </li> <li> <p>MobilePhoneNumber</p> </li> <li> <p>EmailAddress</p> </li> <li> <p>PersonalEmailAddress</p> </li> <li> <p>BusinessEmailAddress</p> </li> <li> <p>FullName</p> </li> </ul> <p>For example, two or more profiles—with spelling mistakes such as <b>John Doe</b> and <b>Jhn Doe</b>, or different casing email addresses such as <b>JOHN_DOE@ANYCOMPANY.COM</b> and <b>johndoe@anycompany.com</b>, or different phone number formats such as <b>555-010-0000</b> and <b>+1-555-010-0000</b>—can be detected as belonging to the same customer <b>John Doe</b> and merged into a unified profile.</p> """,
    tags=['domain_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def get_matches(
    next_token: Optional[constr(min_length=1, max_length=1024)] = Query(
        None, alias='next-token'
    ),
    max_results: Optional[conint(ge=1, le=100)] = Query(None, alias='max-results'),
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/domains/{DomainName}/object-types',
    description=""" Lists all of the templates available within the service. """,
    tags=['domain_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def list_profile_object_types(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    next_token: Optional[constr(min_length=1, max_length=1024)] = Query(
        None, alias='next-token'
    ),
    max_results: Optional[conint(ge=1, le=100)] = Query(None, alias='max-results'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/domains/{DomainName}/object-types/{ObjectTypeName}',
    description=""" Removes a ProfileObjectType from a specific domain as well as removes all the ProfileObjects of that type. It also disables integrations from this specific ProfileObjectType. In addition, it scrubs all of the fields of the standard profile that were populated from this ProfileObjectType. """,
    tags=['user_profile_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def delete_profile_object_type(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    object_type_name: constr(
        pattern=r'^[a-zA-Z_][a-zA-Z_0-9-]*$', min_length=1, max_length=255
    ) = Path(..., alias='ObjectTypeName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/domains/{DomainName}/object-types/{ObjectTypeName}',
    description=""" Returns the object types for a specific domain. """,
    tags=['user_profile_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def get_profile_object_type(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    object_type_name: constr(
        pattern=r'^[a-zA-Z_][a-zA-Z_0-9-]*$', min_length=1, max_length=255
    ) = Path(..., alias='ObjectTypeName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/domains/{DomainName}/object-types/{ObjectTypeName}',
    description=""" <p>Defines a ProfileObjectType.</p> <p>To add or remove tags on an existing ObjectType, see <a href="https://docs.aws.amazon.com/customerprofiles/latest/APIReference/API_TagResource.html"> TagResource</a>/<a href="https://docs.aws.amazon.com/customerprofiles/latest/APIReference/API_UntagResource.html">UntagResource</a>.</p> """,
    tags=['domain_management', 'user_profile_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def put_profile_object_type(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    object_type_name: constr(
        pattern=r'^[a-zA-Z_][a-zA-Z_0-9-]*$', min_length=1, max_length=255
    ) = Path(..., alias='ObjectTypeName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: DomainsDomainNameObjectTypesObjectTypeNamePutRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/domains/{DomainName}/profiles',
    description=""" <p>Creates a standard profile.</p> <p>A standard profile represents the following attributes for a customer profile in a domain.</p> """,
    tags=['domain_management', 'user_profile_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def create_profile(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: DomainsDomainNameProfilesPostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/domains/{DomainName}/profiles',
    description=""" <p>Updates the properties of a profile. The ProfileId is required for updating a customer profile.</p> <p>When calling the UpdateProfile API, specifying an empty string value means that any existing value will be removed. Not specifying a string value means that any value already there will be kept.</p> """,
    tags=['domain_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def update_profile(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: DomainsDomainNameProfilesPutRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/domains/{DomainName}/profiles/delete',
    description=""" Deletes the standard customer profile and all data pertaining to the profile. """,
    tags=['domain_management', 'user_profile_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def delete_profile(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: DomainsDomainNameProfilesDeletePostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/domains/{DomainName}/profiles/keys',
    description=""" <p>Associates a new key value with a specific profile, such as a Contact Record ContactId.</p> <p>A profile object can have a single unique key and any number of additional keys that can be used to identify the profile that it belongs to.</p> """,
    tags=['domain_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def add_profile_key(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: DomainsDomainNameProfilesKeysPostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/domains/{DomainName}/profiles/keys/delete',
    description=""" Removes a searchable key from a customer profile. """,
    tags=['domain_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def delete_profile_key(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: DomainsDomainNameProfilesKeysDeletePostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/domains/{DomainName}/profiles/objects',
    description=""" Returns a list of objects associated with a profile of a given ProfileObjectType. """,
    tags=['domain_management', 'user_profile_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def list_profile_objects(
    next_token: Optional[constr(min_length=1, max_length=1024)] = Query(
        None, alias='next-token'
    ),
    max_results: Optional[conint(ge=1, le=100)] = Query(None, alias='max-results'),
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: DomainsDomainNameProfilesObjectsPostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/domains/{DomainName}/profiles/objects',
    description=""" <p>Adds additional objects to customer profiles of a given ObjectType.</p> <p>When adding a specific profile object, like a Contact Record, an inferred profile can get created if it is not mapped to an existing profile. The resulting profile will only have a phone number populated in the standard ProfileObject. Any additional Contact Records with the same phone number will be mapped to the same inferred profile.</p> <p>When a ProfileObject is created and if a ProfileObjectType already exists for the ProfileObject, it will provide data to a standard profile depending on the ProfileObjectType definition.</p> <p>PutProfileObject needs an ObjectType, which can be created using PutProfileObjectType.</p> """,
    tags=['domain_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def put_profile_object(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: DomainsDomainNameProfilesObjectsPutRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/domains/{DomainName}/profiles/objects/delete',
    description=""" Removes an object associated with a profile of a given ProfileObjectType. """,
    tags=['domain_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def delete_profile_object(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: DomainsDomainNameProfilesObjectsDeletePostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/domains/{DomainName}/profiles/objects/merge',
    description=""" <p>Runs an AWS Lambda job that does the following:</p> <ol> <li> <p>All the profileKeys in the <code>ProfileToBeMerged</code> will be moved to the main profile.</p> </li> <li> <p>All the objects in the <code>ProfileToBeMerged</code> will be moved to the main profile.</p> </li> <li> <p>All the <code>ProfileToBeMerged</code> will be deleted at the end.</p> </li> <li> <p>All the profileKeys in the <code>ProfileIdsToBeMerged</code> will be moved to the main profile.</p> </li> <li> <p>Standard fields are merged as follows:</p> <ol> <li> <p>Fields are always "union"-ed if there are no conflicts in standard fields or attributeKeys.</p> </li> <li> <p>When there are conflicting fields:</p> <ol> <li> <p>If no <code>SourceProfileIds</code> entry is specified, the main Profile value is always taken. </p> </li> <li> <p>If a <code>SourceProfileIds</code> entry is specified, the specified profileId is always taken, even if it is a NULL value.</p> </li> </ol> </li> </ol> </li> </ol> <p>You can use MergeProfiles together with <a href="https://docs.aws.amazon.com/customerprofiles/latest/APIReference/API_GetMatches.html">GetMatches</a>, which returns potentially matching profiles, or use it with the results of another matching system. After profiles have been merged, they cannot be separated (unmerged).</p> """,
    tags=['domain_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def merge_profiles(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: DomainsDomainNameProfilesObjectsMergePostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/domains/{DomainName}/profiles/search',
    description=""" <p>Searches for profiles within a specific domain using one or more predefined search keys (e.g., _fullName, _phone, _email, _account, etc.) and/or custom-defined search keys. A search key is a data type pair that consists of a <code>KeyName</code> and <code>Values</code> list.</p> <p>This operation supports searching for profiles with a minimum of 1 key-value(s) pair and up to 5 key-value(s) pairs using either <code>AND</code> or <code>OR</code> logic.</p> """,
    tags=['domain_management', 'identity_resolution_jobs', 'user_profile_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def search_profiles(
    next_token: Optional[constr(min_length=1, max_length=1024)] = Query(
        None, alias='next-token'
    ),
    max_results: Optional[conint(ge=1, le=100)] = Query(None, alias='max-results'),
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: DomainsDomainNameProfilesSearchPostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/domains/{DomainName}/workflows',
    description=""" Query to list all workflows. """,
    tags=['domain_management', 'identity_resolution_jobs'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def list_workflows(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    next_token: Optional[constr(min_length=1, max_length=1024)] = Query(
        None, alias='next-token'
    ),
    max_results: Optional[conint(ge=1, le=100)] = Query(None, alias='max-results'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: DomainsDomainNameWorkflowsPostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/domains/{DomainName}/workflows/integrations',
    description="""  Creates an integration workflow. An integration workflow is an async process which ingests historic data and sets up an integration for ongoing updates. The supported Amazon AppFlow sources are Salesforce, ServiceNow, and Marketo.  """,
    tags=['domain_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def create_integration_workflow(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: DomainsDomainNameWorkflowsIntegrationsPostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/domains/{DomainName}/workflows/{WorkflowId}',
    description=""" Deletes the specified workflow and all its corresponding resources. This is an async process. """,
    tags=['workflow_definition_management', 'identity_resolution_jobs'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def delete_workflow(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    workflow_id: constr(min_length=1, max_length=255) = Path(..., alias='WorkflowId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/domains/{DomainName}/workflows/{WorkflowId}',
    description=""" Get details of specified workflow. """,
    tags=['workflow_definition_management', 'identity_resolution_jobs'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def get_workflow(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    workflow_id: constr(pattern=r'[a-f0-9]{32}') = Path(..., alias='WorkflowId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/domains/{DomainName}/workflows/{WorkflowId}/steps',
    description=""" Get granular list of steps in workflow. """,
    tags=['workflow_definition_management', 'domain_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def get_workflow_steps(
    domain_name: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='DomainName'),
    workflow_id: constr(pattern=r'[a-f0-9]{32}') = Path(..., alias='WorkflowId'),
    next_token: Optional[constr(min_length=1, max_length=1024)] = Query(
        None, alias='next-token'
    ),
    max_results: Optional[conint(ge=1, le=100)] = Query(None, alias='max-results'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/integrations',
    description=""" Lists all of the integrations associated to a specific URI in the AWS account. """,
    tags=['integration_account_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def list_account_integrations(
    next_token: Optional[constr(min_length=1, max_length=1024)] = Query(
        None, alias='next-token'
    ),
    max_results: Optional[conint(ge=1, le=100)] = Query(None, alias='max-results'),
    include_hidden: Optional[bool] = Query(None, alias='include-hidden'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: IntegrationsPostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/tags/{resourceArn}',
    description=""" Displays the tags associated with an Amazon Connect Customer Profiles resource. In Connect Customer Profiles, domains, profile object types, and integrations can be tagged. """,
    tags=['user_profile_management', 'profile_template_handling'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def list_tags_for_resource(
    resource_arn: constr(pattern=r'^arn:[a-z0-9]{1,10}:profile', max_length=256) = Path(
        ..., alias='resourceArn'
    ),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/tags/{resourceArn}',
    description=""" <p>Assigns one or more tags (key-value pairs) to the specified Amazon Connect Customer Profiles resource. Tags can help you organize and categorize your resources. You can also use them to scope user permissions by granting a user permission to access or change only resources with certain tag values. In Connect Customer Profiles, domains, profile object types, and integrations can be tagged.</p> <p>Tags don't have any semantic meaning to AWS and are interpreted strictly as strings of characters.</p> <p>You can use the TagResource action with a resource that already has tags. If you specify a new tag key, this tag is appended to the list of tags associated with the resource. If you specify a tag key that is already associated with the resource, the new tag value that you specify replaces the previous value for that tag.</p> <p>You can associate as many as 50 tags with a resource.</p> """,
    tags=['integration_account_management', 'resource_tagging_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def tag_resource(
    resource_arn: constr(pattern=r'^arn:[a-z0-9]{1,10}:profile', max_length=256) = Path(
        ..., alias='resourceArn'
    ),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: TagsResourceArnPostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/tags/{resourceArn}#tagKeys',
    description=""" Removes one or more tags from the specified Amazon Connect Customer Profiles resource. In Connect Customer Profiles, domains, profile object types, and integrations can be tagged. """,
    tags=['integration_account_management', 'resource_tagging_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def untag_resource(
    resource_arn: constr(pattern=r'^arn:[a-z0-9]{1,10}:profile', max_length=256) = Path(
        ..., alias='resourceArn'
    ),
    tag_keys: TagKeys = Query(..., alias='tagKeys'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/templates',
    description=""" Lists all of the template information for object types. """,
    tags=['identity_resolution_jobs'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def list_profile_object_type_templates(
    next_token: Optional[constr(min_length=1, max_length=1024)] = Query(
        None, alias='next-token'
    ),
    max_results: Optional[conint(ge=1, le=100)] = Query(None, alias='max-results'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/templates/{TemplateId}',
    description=""" <p>Returns the template information for a specific object type.</p> <p>A template is a predefined ProfileObjectType, such as “Salesforce-Account” or “Salesforce-Contact.” When a user sends a ProfileObject, using the PutProfileObject API, with an ObjectTypeName that matches one of the TemplateIds, it uses the mappings from the template.</p> """,
    tags=['profile_template_handling'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def get_profile_object_type_template(
    template_id: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=64
    ) = Path(..., alias='TemplateId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
